### ISSUE TITLE
NPM install on Windows XX fails

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/docs.blockstack#236]
I have the following error when attempting to install the npm dependencies for animal kingdom (Note my npm version is 6.9.0 and node.js version is 12.0.0):
PS C:\animal-kingdom> npm install

```
tiny-secp256k1@1.1.0 install C:\animal-kingdom\node_modules\tiny-secp256k1
node-gyp rebuild

C:\animal-kingdom\node_modules\tiny-secp256k1>if not defined npm_config_node_gyp (node “C:\Users\Owner\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\…\node_modules\node-gyp\bin\node-gyp.js” rebuild ) else (node “C:\Users\Owner\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js” rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the “/m” switch.
addon.cpp
win_delay_load_hook.cc
c:\animal-kingdom\node_modules\tiny-secp256k1\native\addon.cpp(320): error C2661: ‘v8::Value::BooleanValue’: no overloaded function takes 0 arguments
[C:\animal-kingdom\node_modules\tiny-secp256k1\build\secp256k1.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Users\Owner\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack at ChildProcess.emit (events.js:196:13)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command “C:\Program Files\nodejs\node.exe” “C:\Users\Owner\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js” “rebuild”
gyp ERR! cwd C:\animal-kingdom\node_modules\tiny-secp256k1
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@3.0.6 requires a peer of babel-eslint@9.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@3.0.6 requires a peer of eslint-plugin-flowtype@2.x but none is installed. You must install peer dependencies yourself.
npm WARN animal-kingdom@1.0.0-alpha.2 No repository field.
npm WARN animal-kingdom@1.0.0-alpha.2 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.6 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.6: wanted {“os”:“darwin”,“arch”:“any”} (current: {“os”:“win32”,“arch”:“x64”})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-secp256k1@1.1.0 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tiny-secp256k1@1.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Owner\AppData\Roaming\npm-cache_logs\2019-04-26T23_18_01_762Z-debug.log
PS C:\animal-kingdom>
```

**Comment by moxiegirl** [comment]
@davisl I actually ran this and ran into a problem even so with `node-gyp`  looks like the issue is only with the current version of `node.js`. The workaround is to use the LTS version installer.  I'm curious, which version of node.js do you have installed?

**Comment by davisl** [comment]
I actually have v10.15.3

**Comment by moxiegirl** [comment]
@davisl Thanks response. Yes, that is what I thought.  You have the LTS version. Our instructions tell users to install the latest which is 12.1.0.  Looks like that version isn't playing nice with the latest version of node-gyp which itself has other issues. I'll adjust the instructions.  Thanks for the issue and glad you got it sorted.
