### ISSUE TITLE
Update app generator project with Blockstack Connect

### ISSUE THREAD

**Issue by markmhx** [blockstack/docs.blockstack#554]
Several tutorials rely on [the app generator](https://github.com/blockstack/blockstack-app-generator) and need it updated to Blockstack Connect:

- [Hello, Blockstack](https://docs.blockstack.org/browser/hello-blockstack.html)
- [Storage](https://docs.blockstack.org/browser/blockstack_storage.html)
- [Deployment](https://docs.blockstack.org/develop/deploy-tips.html)
- [Android DApps](https://docs.blockstack.org/android/tutorial.html)
- [iOS Dapps](https://docs.blockstack.org/ios/tutorial.html)

The written content of these tutorials need to be updated to correspond to the changes made to the app generator upon updating to Blockstack Connect. However, those written content updates are tracked in separate issues.

**Comment by timstackblock** [comment]
My local version of connect is throwing this issue when I run yarn dev, this always worked for me any ideas on what might have changed with the setup?



```TWs-MacBook-Pro:ux tw$ yarn dev
yarn run v1.22.0
$ NODE_ENV=development yarn lerna exec --parallel 'yarn dev' --scope test-app --scope @blockstack/app
$ /Users/tw/ux/node_modules/.bin/lerna exec --parallel 'yarn dev' --scope test-app --scope @blockstack/app
lerna notice cli v3.20.2
lerna info versioning independent
lerna notice filter including ["test-app","@blockstack/app"]
lerna info filter [ 'test-app', '@blockstack/app' ]
lerna info Executing command in 2 packages: "yarn dev"
@blockstack/app: $ cross-env NODE_ENV=development webpack-dev-server --hot --mode development
test-app: $ cross-env NODE_ENV=development webpack-dev-server --hot --mode development
@blockstack/app: events.js:292
@blockstack/app:       throw er; // Unhandled 'error' event
@blockstack/app:       ^
@blockstack/app: Error: spawn webpack-dev-server ENOENT
@blockstack/app:     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
@blockstack/app:     at onErrorNT (internal/child_process.js:467:16)
@blockstack/app:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
@blockstack/app: Emitted 'error' event on ChildProcess instance at:
@blockstack/app:     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
@blockstack/app:     at onErrorNT (internal/child_process.js:467:16)
@blockstack/app:     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
@blockstack/app:   errno: -2,
@blockstack/app:   code: 'ENOENT',
@blockstack/app:   syscall: 'spawn webpack-dev-server',
@blockstack/app:   path: 'webpack-dev-server',
@blockstack/app:   spawnargs: [ '--hot', '--mode', 'development' ]
@blockstack/app: }
test-app: events.js:292
test-app:       throw er; // Unhandled 'error' event
test-app:       ^
test-app: Error: spawn webpack-dev-server ENOENT
test-app:     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
test-app:     at onErrorNT (internal/child_process.js:467:16)
test-app:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
test-app: Emitted 'error' event on ChildProcess instance at:
test-app:     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
test-app:     at onErrorNT (internal/child_process.js:467:16)
test-app:     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
test-app:   errno: -2,
test-app:   code: 'ENOENT',
test-app:   syscall: 'spawn webpack-dev-server',
test-app:   path: 'webpack-dev-server',
test-app:   spawnargs: [ '--hot', '--mode', 'development' ]
test-app: }
@blockstack/app: error Command failed with exit code 1.
@blockstack/app: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
test-app: error Command failed with exit code 1.
test-app: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn dev exited 1 in '@blockstack/app'
lerna ERR! yarn dev stdout:
$ cross-env NODE_ENV=development webpack-dev-server --hot --mode development
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn dev stderr:
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack-dev-server ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn webpack-dev-server',
  path: 'webpack-dev-server',
  spawnargs: [ '--hot', '--mode', 'development' ]
}
error Command failed with exit code 1.

lerna ERR! yarn dev exited 1 in '@blockstack/app'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
TWs-MacBook-Pro:ux tw$ 
```

**Comment by timstackblock** [comment]
I just ran the generator and its still pulling blockstack browser.

**Comment by timstackblock** [comment]
I have the the connect app running locally on port 3000 and I have installed the feature/connect branch and ran the app generator locally but it still seems to open with blockstack browser. See images below.

![Screen Shot 2020-05-13 at 9.17.50 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/5bde647e-b69e-4912-92b9-cb05b73b379c)

Now I launch the updated version of the app generator and I am expecting it to use the connect app.

![Screen Shot 2020-05-13 at 9.34.22 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/2b1aae99-c48c-4523-946a-792f5c9c7236)

![Screen Shot 2020-05-13 at 9.29.53 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/2a1825c0-de24-432c-b13c-9b05fb285c14)
